// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxYU4yNtqIhb3FLzm4vGKvBEcMCFaH6Iw',
    appId: '1:921104231407:web:0a0e50b9a10d4f18a1e41a',
    messagingSenderId: '921104231407',
    projectId: 'reminder-35dee',
    authDomain: 'reminder-35dee.firebaseapp.com',
    storageBucket: 'reminder-35dee.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgTiynf64KBoG6s9y4E65x4t9esmCBJoM',
    appId: '1:921104231407:android:3c4d98effcd24ec2a1e41a',
    messagingSenderId: '921104231407',
    projectId: 'reminder-35dee',
    storageBucket: 'reminder-35dee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYyw0G_IpC26JLWPumwiHZ4G8Tj9X6Cdg',
    appId: '1:921104231407:ios:24640bef8dd0021ca1e41a',
    messagingSenderId: '921104231407',
    projectId: 'reminder-35dee',
    storageBucket: 'reminder-35dee.appspot.com',
    iosBundleId: 'com.example.reminderApp',
  );
}
